214247C_ICA1/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace _214247C_ICA1.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [MinLength(12, ErrorMessage = "Enter at least a 12 characters password")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{12,}$", ErrorMessage = "Passwords must be at least 12 characters long and contain at least an uppercase letter, lower case letter, digit and a symbol")]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
	}
}

214247C_ICA1/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace _214247C_ICA1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

214247C_ICA1/Pages/Index.cshtml.cs
using _214247C_ICA1.Model;
using _214247C_ICA1.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace _214247C_ICA1.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        [BindProperty]
        //getting from app identityyy
        public ApplicationUser UserIden { get; set; }

        private readonly ILogger<IndexModel> _logger;
        private IDataProtectionProvider _dataProtectionProvider;
        private readonly UserManager<ApplicationUser> _userManager;

        private SignInManager<ApplicationUser> _signInManager { get; }

        public IndexModel(ILogger<IndexModel> logger, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IDataProtectionProvider dataProtectionProvider)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _dataProtectionProvider = dataProtectionProvider;
            _logger = logger;
        }
        public async Task OnGet()
        {
            UserIden = await _userManager.GetUserAsync(User);
            var protector = _dataProtectionProvider.CreateProtector("MySecretKey");
            var user = await _userManager.GetUserAsync(User);
            user.NRIC = protector.Unprotect(user.NRIC);
            //System.Diagnostics.Debug.WriteLine(decrypted);
        }
    }
}

214247C_ICA1/Pages/Login.cshtml.cs
using _214247C_ICA1.Model;
using _214247C_ICA1.ViewModels;
using AspNetCore.ReCaptcha;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace _214247C_ICA1.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login LModel { get; set; }

        private UserManager<ApplicationUser> userManager { get; }

        private readonly SignInManager<ApplicationUser> signInManager;
        public LoginModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }
        // check whether is the user a not.
        public void OnGet()
        {
        }
		[ValidateReCaptcha]
		public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
                LModel.RememberMe, false);
                if (identityResult.Succeeded)
                {
                    //Create the security context
                    var claims = new List<Claim> {
                        new Claim(ClaimTypes.Name, "c@c.com"),
                        new Claim(ClaimTypes.Email, "c@c.com"),
                        new Claim("Membership", "HR")
                    };
                    var i = new ClaimsIdentity(claims, "MyCookieAuth");
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(i);
                    await HttpContext.SignInAsync("MyCookieAuth", claimsPrincipal);

                    return RedirectToPage("/Index");
                }
                ModelState.AddModelError("", "Username or Password incorrect");
            }
            return Page();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(Login login)
        {
            if (ModelState.IsValid)
            {
                var User = await userManager.FindByEmailAsync(login.Email);
                if (User != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(User, login.Password, false, true);
                    if (result.Succeeded)
                        return RedirectToPage("/Index");

                    if (result.IsLockedOut)
                        ModelState.AddModelError("", "Your account is locked out. Kindly wait for 2 minutes and try again");
                }
                ModelState.AddModelError(nameof(login.Email), "Login Failed: Invalid Email or password");
            }
            return RedirectToPage("/Login");
        }
    }
}

214247C_ICA1/Pages/Logout.cshtml.cs
using _214247C_ICA1.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _214247C_ICA1.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        // kill the session and clean the session away; SignOutAsync
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("/Login");
        }
        // this guy will go back to the index page
        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("/Index");
        }
    }
}

214247C_ICA1/Pages/Membership.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _214247C_ICA1.Pages
{
    [Authorize(Policy ="Membership")]
    public class MembershipModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

214247C_ICA1/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _214247C_ICA1.Pages
{
    [Authorize(Roles = "Admin")]
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

214247C_ICA1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="text-center">
    <h4>Welcome @Model.UserIden.Fname @Model.UserIden.Lname </h4>
    <p><small>with NRIC of @Model.UserIden.NRIC :></small></p>
</div>

214247C_ICA1/Pages/Login.cshtml
@page
@model _214247C_ICA1.Pages.LoginModel
@{
}
@using AspNetCore.ReCaptcha

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post">
				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="Text" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>
				@Html.ReCaptcha()
				<recaptcha/>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>
			</form>
		</div>
		<div class="mt-4">
			<div class="d-flex justify-content-center links">
				Don't have an account? <a asp-page="/Shared/Register" class="ml-2">Sign Up</a>
			</div>
			<div class="d-flex justify-content-center links">
				<a asp-page="/Account/ResetPassword">Forgot your password?</a>
			</div>
		</div>
	</div>
</div>

214247C_ICA1/Pages/Logout.cshtml
@page
@model _214247C_ICA1.Pages.LogoutModel
@{
}
<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p>
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>
	</div>
</form>

214247C_ICA1/Pages/Membership.cshtml
@page
@model _214247C_ICA1.Pages.MembershipModel
@{
}
<div class="text-center">
    <h5 class="display-4">Membership page!</h5>
</div>